# Change these first
owner: gilkobra # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
user-agent: kobra-uptime # The user-agent, which is the name of the bot making the requests

sites:
  - name: Sitio Público
    url: https://kobra.red
    headers:
      - "User-Agent: kobra-uptime"
  - name: Admin
    url: https://admin.kobra.red
    headers:
      - "User-Agent: kobra-uptime"
  - name: AppsServices (lean-services)
    url: https://apps.kobra.red/s1/lean-services/
    headers:
      - "User-Agent: kobra-uptime"
  - name: AppsServices (visitas)
    url: https://apps.kobra.red/s1/visitas/
    headers:
      - "User-Agent: kobra-uptime"
  - name: AppsServices (storage)
    url: https://apps.kobra.red/s1/storage/
    headers:
      - "User-Agent: kobra-uptime"
  - name: AppsServices (kobra-saldos)
    url: https://apps.kobra.red/s1/kobra-saldos/
    headers:
      - "User-Agent: kobra-uptime"
  
assignees: # Users to assign downtime issues (optional)
  - gilkobra

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kobra.red
  # baseUrl: /uptime
  logoUrl: https://kobra.red/wp-content/uploads/2024/05/classe-Canva-1.png
  robotsText: "User-agent: * \n Disallow: /"
  name: Uptime | Kobra
  introTitle: "**Uptime kobra.red**"
  introMessage: Esta es una página pública para mostrar el estatus de todos nuestros servicios.
  navbar:
    # - title: Status
    #   href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO
    - title: Ir a la página principal
      href: https://kobra.red
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration